"""add role column

Revision ID: 065a624949cb
Revises: 07333bd7bcf3
Create Date: 2026-06-02 13:36:57.226022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065a624949cb'
down_revision = '07333bd7bcf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('service_stage',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('service_stage',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
